GoleadaApp/MVC/Controllers/GolesController.cs
using DAL.Entities.EDMX;
using Entities.DTO;
using Entities.VM;
using MVC.Models;
using Newtonsoft.Json;
using Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class GolesController : Controller
    {
        private readonly GolesService GolesService;
        private readonly JugadoresService JugadoresService;
        public GolesController()
        {
            GoleadaDBEntities contexto = new GoleadaDBEntities();
            GolesService = new GolesService(contexto);
            JugadoresService = new JugadoresService(contexto);
        }
        public ActionResult ListaGolesJugador()
        {
            List<GolesPorJugadorEquipo> Goles = GolesService.ObtenerTodos();
            return View(Goles);
        }
        public ActionResult AltaGolesJugador()
        {
            ViewBag.ListaJugadores = JugadoresService.ObtenerComboJugadores();
            return View();
        }

        [HttpPost]
        public ActionResult AltaGolesJugador(GolesPorJugadorEquipo goles)
        {
            if (!ModelState.IsValid)
            {
                TempData["Creado"] = "FALSE";
                ViewBag.ListaJugadores = JugadoresService.ObtenerComboJugadores(goles.IdJugador);
                return View(goles);
            }

            GolesService.AltaModificacion(goles);
            TempData["Creado"] = JugadoresService.ObtenerPorId(goles.IdJugador).Nombre.ToString();
            return RedirectToAction("ListaGolesJugador");
        }

        public ActionResult GolesPruebaApi(string id)
        {
            ViewBag.Equipo = id;
            ViewBag.Cant = GetGolesEquipo(id);
            return View();
        }

        private string GetGolesEquipo(string id)
        {
            var url = $"https://localhost:44350/api/cantidadtotalgolesequipoapi/{id}";
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "GET";
            request.ContentType = "application/json";
            request.Accept = "application/json";

            using (WebResponse response = request.GetResponse())
            {
                using (Stream strReader = response.GetResponseStream())
                {
                    if (strReader == null) return id;
                    using (StreamReader objReader = new StreamReader(strReader))
                    {
                        string responseBody = objReader.ReadToEnd();
                        var result = JsonConvert.DeserializeObject<string>(responseBody);
                        return result;
                    }
                }
            }
        }

        public ActionResult GolesDTOApi()
        {
            List<GolesDTO> goles = GetGolesDTOApi();
            return View(goles);
        }

        private List<GolesDTO> GetGolesDTOApi()
        {
            var url = $"https://localhost:44350/api/golesdtoapi";
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "GET";
            request.ContentType = "application/json";
            request.Accept = "application/json";

            using (WebResponse response = request.GetResponse())
            {
                using (Stream strReader = response.GetResponseStream())
                {
                    if (strReader == null) return new List<GolesDTO>();
                    using (StreamReader objReader = new StreamReader(strReader))
                    {
                        string responseBody = objReader.ReadToEnd();
                        var result = JsonConvert.DeserializeObject<List<GolesDTO>>(responseBody);
                        return result;
                    }
                }
            }
        }

        public ActionResult GolesServerSide()
        {
            return View();
        }
        public ActionResult GetData(JqueryDatatableParam param)
        {
            List<GolesDTO> employees = GetGolesDTOApi();

            //employees.ToList().ForEach(x => x.StartDateString = x.StartDate.ToString("dd'/'MM'/'yyyy"));

            if (!string.IsNullOrEmpty(param.sSearch))
            {
                employees = employees.Where(x => x.Cantidad.ToString().Contains(param.sSearch.ToLower())
                                              || x.Equipo.ToLower().Contains(param.sSearch.ToLower())
                                              || x.NombreJugador.ToLower().Contains(param.sSearch.ToLower())).ToList();
            }

            var sortColumnIndex = Convert.ToInt32(HttpContext.Request.QueryString["iSortCol_0"]);
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];

            if (sortColumnIndex == 3)
            {
                employees = (sortDirection == "asc" ? employees.OrderBy(c => c.Cantidad).ToList() : employees.OrderByDescending(c => c.Cantidad).ToList());
            }
            else if (sortColumnIndex == 4)
            {
                employees = (sortDirection == "asc" ? employees.OrderBy(c => c.Equipo).ToList() : employees.OrderByDescending(c => c.Equipo).ToList());
            }
            else if (sortColumnIndex == 5)
            {
                employees = (sortDirection == "asc" ? employees.OrderBy(c => c.NombreJugador).ToList() : employees.OrderByDescending(c => c.NombreJugador).ToList());
            }
            else
            {
                Func<GolesDTO, string> orderingFunction = e => sortColumnIndex == 0 ? e.NombreJugador :
                                                               sortColumnIndex == 1 ? e.Equipo :
                                                               e.Cantidad.ToString();

                employees = sortDirection == "asc" ? employees.OrderBy(orderingFunction).ToList() : employees.OrderByDescending(orderingFunction).ToList();
            }

            var displayResult = employees.Skip(param.iDisplayStart)
                .Take(param.iDisplayLength).ToList();
            var totalRecords = employees.Count();

            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GolesEquipo()
        {
            List<GolesEquipoVM> golesEquipos = GolesService.GolesPorEquipo();
            return View(golesEquipos);
        }
    }
}

GoleadaApp/MVC/Views/Goles/AltaGolesJugador.cshtml
@model DAL.Entities.EDMX.GolesPorJugadorEquipo

@{
    ViewBag.Title = "Alta de Goles para un Jugador";
}

@if (TempData["Creado"] != null && (string)TempData["Creado"] == "FALSE")
{
    <div class="alert alert-danger alert-dismissible fade show text-center mt-5" role="alert">
        Error al crear registro de goles del jugador
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5">

    <h2>Registrar goles de un jugador</h2>

    @Html.ActionLink("Ir a Listado de Goles por Jugador", "ListaGolesJugador", "Goles", null, new { @class = "btn btn-success" })

</div>

<p>A continuación puede registrar un jugador con sus goles en un equipo</p>
<hr class="mb-5" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label">Jugadores</label>
            <div class="col-md-10 col-lg-6 px-0">
                @Html.DropDownListFor(model => model.IdJugador, (List<SelectListItem>)ViewBag.ListaJugadores, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdJugador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Equipo</label>
            <div class="col-md-10 col-lg-6 px-0">
                @Html.EditorFor(model => model.Equipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Equipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">Cantidad de goles</label>
            <div class="col-md-10 col-lg-6 px-0">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 px-0">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

GoleadaApp/MVC/Views/Goles/GolesDTOApi.cshtml
@model List<Entities.DTO.GolesDTO>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Equipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NombreJugador)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Equipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreJugador)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id}) |
                @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

GoleadaApp/MVC/Views/Goles/GolesEquipo.cshtml
@model List<Entities.VM.GolesEquipoVM>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-bordered table-hover">
        <tr class="bg-light">
            <th>
                @Html.DisplayNameFor(model => model.First().Equipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().PromedioJugadores)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Equipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PromedioJugadores)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }

    </table>

GoleadaApp/MVC/Views/Goles/GolesPruebaApi.cshtml
<div class="jumbotron my-5">
    <h1 class="display-4">Prueba de la API</h1>

    <p class="lead my-4">A continuación se muestra la cantidad de goles para el equipo solicitado:</p>


    <p class="lead my-4"><strong>@ViewBag.Equipo :</strong> @ViewBag.Cant goles en total.</p>

    <a href="/Goles/ListaGolesJugador" class="btn btn-success btn-lg">Volver al listado de Goles</a>
</div>

GoleadaApp/MVC/Views/Goles/GolesServerSide.cshtml
@{
    ViewBag.Title = "Goles Server Side";
}

<link href="~/Content/Tables/jquery.dataTables.min.css" rel="stylesheet" />


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5">

    <h2>Goles con tabla Server Side</h2>

    @Html.ActionLink("Ir a Listado de Goles por Jugador", "ListaGolesJugador", "Goles", null, new { @class = "btn btn-success" })

</div>

<p>A continuación puede registrar un jugador con sus goles en un equipo</p>
<hr class="mb-5" />
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-striped" id="tblStudent">
            <thead>
                <tr>
                    <th scope="col">Equipo</th>
                    <th scope="col">Cantidad de goles</th>
                    <th scope="col">Jugador</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<link href="~/Content/Tables/datatables.min.css" rel="stylesheet" />
<script src="~/Scripts/tables/dataTables.js"></script>
<script src="~/Scripts/tables/datatables.min.js"></script>

GoleadaApp/MVC/Views/Goles/ListaGolesJugador.cshtml
@model List<DAL.Entities.EDMX.GolesPorJugadorEquipo>

@{
    ViewBag.Title = "Lista Goles";
}


@if (TempData["Creado"] != null && (string)TempData["Creado"] != "FALSE")
{
    <div class="alert alert-success alert-dismissible fade show text-center mt-5" role="alert">
        ¡Registro de jugador <strong>@TempData["Creado"].ToString()</strong> creado correctamente!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5">

    <h2>Listado de Jugadores y sus Goles</h2>

    @Html.ActionLink("Crear Nuevo Registro de Goles", "AltaGolesJugador", null, new { @class = "btn btn-success" })

</div>

<p>A continuación se muestra la lista de todos los jugadores con sus goles por equipo</p>
<hr class="mb-5" />

<table class="table table-bordered table-hover">
    <tr class="bg-light">
        <th>
            Equipo
        </th>
        <th>
            Catidad de Goles
        </th>
        <th>
            Jugador
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Equipo, "GolesPruebaApi", new { id = item.Equipo }, new { @class = "" })
            </td>
            <td>
                @item.Cantidad
            </td>
            <td>
                @item.Jugador.Nombre
            </td>
        </tr>
    }

</table>