GoleadaApp/MVC/Controllers/JugadoresController.cs
using DAL.Entities.EDMX;
using Entities.VM;
using Services;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class JugadoresController : Controller
    {
        JugadoresService JugadoresService;
        public JugadoresController()
        {
            GoleadaDBEntities contexto = new GoleadaDBEntities();
            JugadoresService = new JugadoresService(contexto);
        }
        public ActionResult ListaJugadores()
        {
            List<Jugador> Jugadores = JugadoresService.ObtenerTodos();
            return View(Jugadores);
        }

        public ActionResult AltaJugadores()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AltaJugadores(JugadoresVM Jugadores)
        {
            if (!JugadoresService.Validar(Jugadores))
            {
                TempData["Creado"] = "FALSE";
                return View(Jugadores);
            }

            if (Jugadores.Nombres.Count() == 1)
            {
                TempData["Creado"] = JugadoresService.AltaJugadores(Jugadores);
            }
            else
            {
                TempData["Creados"] = JugadoresService.AltaJugadores(Jugadores);
            }
            return RedirectToAction("ListaJugadores");
        }

    }
}

GoleadaApp/MVC/Views/Jugadores/AltaJugador.cshtml
@model DAL.Entities.EDMX.Jugador

@{
    ViewBag.Title = "Alta de Goles para un Jugador";
}

@if (TempData["Creado"] != null && (string)TempData["Creado"] == "FALSE")
{
    <div class="alert alert-danger alert-dismissible fade show text-center mt-5" role="alert">
        ¡Error al intentar crear al jugador!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5">

    <h2>Registrar jugador</h2>

    @Html.ActionLink("Ir a Listado de Jugadores", "ListaJugadores", "Jugadores", null, new { @class = "btn btn-success" })

</div>

<p>A continuación puede registrar un jugador con sus goles en un equipo</p>
<hr class="mb-5" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label">Nombre</label>
            <div class="col-md-10 col-lg-6 px-0">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 px-0">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

GoleadaApp/MVC/Views/Jugadores/AltaJugadores.cshtml
@{
    ViewBag.Title = "Alta de muchos Jugadores";
}

@Styles.Render("~/Content/dragula")

@if (TempData["Creado"] != null && (string)TempData["Creado"] == "FALSE")
{
    <div class="alert alert-danger alert-dismissible fade show text-center mt-5" role="alert">
        ¡Error al intentar crear jugadores!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5">

    <h2>Registrar jugadores</h2>

    @Html.ActionLink("Ir a Listado de Jugadores", "ListaJugadores", "Jugadores", null, new { @class = "btn btn-success" })

</div>

<p>A continuación puede registrar varios jugadores</p>
<hr class="mb-5" />

<form action="AltaJugadores" method="post" onsubmit="return validar()">

    <div class="form-horizontal">

        <div id="form">

            <div class="form-group form-jug" id="form_1">
                <label class="control-label">Nombre Jugador</label>
                <div class="col-md-10 col-lg-6 px-0">
                    <div class="row mx-0">
                        <div class="col-9 px-0">
                            <input class="form-control input-jug text-box "
                                   id="Nombre_1" name="Nombres[]" type="text" value="">
                        </div>
                        <div class="col px-0 pl-4">
                            <input onclick="remove()" id="remove_1" type="button" class="btn btn-danger btn-jug remove d-none" value="-">
                        </div>
                    </div>
                    <span id="msg_1" class="text-danger msg-val"></span>
                </div>

            </div>

            <div id="form-mov">

                <div class="form-group form-jug" id="form_2">
                    <label class="control-label">Nombre Jugador</label>
                    <div class="col-md-10 col-lg-6 px-0">
                        <div class="row mx-0">
                            <div class="col-9 px-0">
                                <input class="form-control input-jug text-box "
                                       id="Nombre_2" name="Nombres[]" type="text" value="">
                            </div>
                            <div class="col px-0 pl-4">
                                <button onclick="remove()" id="remove_2" type="button" class="btn btn-danger btn-jug remove" value="-">
                                    <ion-icon name="remove-outline"></ion-icon>
                                </button>
                            </div>
                            <div class="col px-0 pl-4">
                                <button type="button" class="btn btn-primary btn-move">
                                    <ion-icon class="btn-move" name="move-outline"></ion-icon>
                                </button>
                            </div>
                        </div>
                        <span id="msg_2" class="msg-val text-danger"></span>
                    </div>
                </div>
            </div>

            <template id="tem-form-jug">
                <div class="form-group form-jug" id="form_tem">
                    <label class="control-label">Nombre Jugador</label>
                    <div class="col-md-10 col-lg-6 px-0">
                        <div class="row mx-0">
                            <div class="col-9 px-0">
                                <input class="form-control input-jug text-box "
                                       name="Nombres[]" type="text" value="">
                            </div>
                            <div class="col px-0 pl-4">
                                <button onclick="remove()" type="button" class="btn btn-danger btn-jug remove">
                                    <ion-icon name="remove-outline"></ion-icon>
                                </button>
                            </div>
                            <div class="col px-0 pl-4">
                                <button type="button" class="btn btn-primary btn-move">
                                    <ion-icon class="btn-move" name="move-outline"></ion-icon>
                                </button>
                            </div>
                        </div>
                        <span id="msg_" class="msg-val text-danger"></span>
                    </div>
                </div>
            </template>

        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 px-0">
            <button id="add" type="button" class="btn btn-primary my-2">Agregar otro</button>
            <input type="submit" value="Guardar" class="btn btn-success" />
        </div>
    </div>

</form>

@Scripts.Render("~/bundles/dragula")
<script src="~/Scripts/custom/abm-jugs.js"></script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>

GoleadaApp/MVC/Views/Jugadores/ListaJugadores.cshtml
@model List<DAL.Entities.EDMX.Jugador>

@{
    ViewBag.Title = "Lista Goles";
}


@if (TempData["Creado"] != null && (string)TempData["Creado"] != "FALSE")
{
    <div class="alert alert-success alert-dismissible fade show text-center mt-5" role="alert">
        ¡El jugador <strong>@TempData["Creado"].ToString()</strong> fue creado correctamente!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["Creados"] != null && (string)TempData["Creados"] != "FALSE")
{
    <div class="alert alert-success alert-dismissible fade show text-center mt-5" role="alert">
        ¡Los jugadores <strong>@TempData["Creados"].ToString()</strong> fueron creados correctamente!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5">

    <h2>Listado de jugadores registrados</h2>

    @Html.ActionLink("Crear Nuevos Jugadores", "AltaJugadores", null, new { @class = "btn btn-success" })

</div>

<p>A continuación se muestra la lista de todos los jugadores registrados</p>
<hr class="mb-5" />

<table class="table table-bordered table-hover">
    <tr class="bg-light">
        <th>
            Nombre
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Nombre
            </td>
        </tr>
    }

</table>